"""Change id columns types to UUIDType

Revision ID: daaeb9e25b46
Revises: 983e38b839f9
Create Date: 2022-01-14 19:17:17.822130

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import fastapi_users_db_sqlalchemy
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'daaeb9e25b46'
down_revision = '983e38b839f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               existing_nullable=False)
        batch_op.alter_column('uploader_id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               existing_nullable=True)

    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               existing_nullable=False)

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               existing_nullable=False)
        batch_op.alter_column('uploader_id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               existing_nullable=True)

    with op.batch_alter_table('routeimage', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               existing_nullable=False)
        batch_op.alter_column('route_id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               existing_nullable=True)
        batch_op.alter_column('image_id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)

    with op.batch_alter_table('routeimage', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)
        batch_op.alter_column('route_id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.alter_column('uploader_id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)

    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('uploader_id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)

    # ### end Alembic commands ###
