"""Remove excess author field and rename uploader field to author field

Revision ID: 4ef06e4a3d65
Revises: 8b0320481e60
Create Date: 2022-02-14 23:46:58.538244

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op
from alembic.operations import BatchOperations

# revision identifiers, used by Alembic.
revision = "4ef06e4a3d65"
down_revision = "8b0320481e60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    batch_op: BatchOperations
    with op.batch_alter_table("route", schema=None) as batch_op:
        batch_op.drop_column("author")
        batch_op.alter_column("uploader_id", new_column_name="author_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("route", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("author", sa.VARCHAR(length=150), nullable=True)
        )
        batch_op.alter_column("author_id", new_column_name="uploader_id")

    # ### end Alembic commands ###
