"""Add AccessRefreshToken table

Revision ID: 5473a80fe510
Revises: 9efd031f2336
Create Date: 2024-03-07 23:46:03.458971

"""

import fastapi_users_db_sqlmodel
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "5473a80fe510"
down_revision = "9efd031f2336"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accessrefreshtoken",
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlmodel.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.Column("refresh_token", sa.String(length=43), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    with op.batch_alter_table("accessrefreshtoken", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accessrefreshtoken_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_accessrefreshtoken_refresh_token"),
            ["refresh_token"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accessrefreshtoken", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accessrefreshtoken_refresh_token"))
        batch_op.drop_index(batch_op.f("ix_accessrefreshtoken_created_at"))

    op.drop_table("accessrefreshtoken")
    # ### end Alembic commands ###
