"""Add created_at column to Route table

Revision ID: 8b0320481e60
Revises: 8d3f23d9f4db
Create Date: 2022-01-25 16:06:38.904793

"""
import sqlalchemy as sa
import sqlmodel

from alembic.migration import MigrationContext
from alembic.op import get_bind, get_context
from alembic.operations import Operations

# revision identifiers, used by Alembic.
revision = "8b0320481e60"
down_revision = "8d3f23d9f4db"
branch_labels = None
depends_on = None

context: MigrationContext = get_context()
op = Operations(context)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("route", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default="2022-01-25 00:00:00.000000",
                nullable=False,
            )
        )
    op.drop_table("_alembic_tmp_route")
    with op.batch_alter_table("route", schema=None) as batch_op:
        batch_op.alter_column("created_at", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("route", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
