"""Add RefreshToken table

Revision ID: 9efd031f2336
Revises: 246635576a0f
Create Date: 2024-03-07 19:12:32.062030

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlmodel


# revision identifiers, used by Alembic.
revision = '9efd031f2336'
down_revision = '246635576a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtoken',
    sa.Column('created_at', fastapi_users_db_sqlmodel.generics.TIMESTAMPAware(timezone=True), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refreshtoken_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refreshtoken_created_at'))

    op.drop_table('refreshtoken')
    # ### end Alembic commands ###
