"""Change user's creation_date column name and type

Revision ID: a30dccf9af29
Revises: daaeb9e25b46
Create Date: 2022-01-14 22:13:14.370516

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a30dccf9af29"
down_revision = "daaeb9e25b46"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "creation_date",
            new_column_name="created_at",
            nullable=False,
            type_=sa.DateTime,
            existing_type=sa.Date,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            new_column_name="creation_date",
            nullable=True,
            type_=sa.Date,
            existing_type=sa.DateTime,
        )

    # ### end Alembic commands ###
