"""Add ON DELETE CASCADE to oauthaccount and accesstoken tables

Revision ID: d931930fbfbe
Revises: 75de8a0aafde
Create Date: 2023-01-21 20:32:27.524421

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "d931930fbfbe"
down_revision = "75de8a0aafde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ascent", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=False
        )

    with op.batch_alter_table("competition", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=False
        )

    with op.batch_alter_table(
        "competitionparticipant", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=False
        )

    with op.batch_alter_table("oauthaccount", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=False
        )

    with op.batch_alter_table("route", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=False
        )

    with op.batch_alter_table("routeimage", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=False
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("routeimage", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), nullable=True
        )
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=True
        )

    with op.batch_alter_table("route", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=True
        )

    with op.batch_alter_table("oauthaccount", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=True
        )

    with op.batch_alter_table(
        "competitionparticipant", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=True
        )

    with op.batch_alter_table("competition", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=sa.DATETIME(), nullable=True
        )

    with op.batch_alter_table("ascent", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.CHAR(length=32), nullable=True
        )

    with op.batch_alter_table("accesstoken", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accesstoken_created_at"))

    # ### end Alembic commands ###
