"""Remove AccessToken and RefreshToken tables

Revision ID: ede4ba9c2dfe
Revises: 5473a80fe510
Create Date: 2024-03-08 03:41:35.766511

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlmodel


# revision identifiers, used by Alembic.
revision = 'ede4ba9c2dfe'
down_revision = '5473a80fe510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.drop_index('ix_refreshtoken_created_at')

    op.drop_table('refreshtoken')
    with op.batch_alter_table('accesstoken', schema=None) as batch_op:
        batch_op.drop_index('ix_accesstoken_created_at')

    op.drop_table('accesstoken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesstoken',
    sa.Column('token', sa.VARCHAR(length=43), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='accesstoken_user_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('accesstoken', schema=None) as batch_op:
        batch_op.create_index('ix_accesstoken_created_at', ['created_at'], unique=False)

    op.create_table('refreshtoken',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=43), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.create_index('ix_refreshtoken_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
