"""Add sex field to User

Revision ID: ef54dbb20760
Revises: ed41c5a8c681
Create Date: 2023-11-03 06:23:26.275077

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "ef54dbb20760"
down_revision = "ed41c5a8c681"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sex",
                sa.Enum("male", "female", name="sexenum"),
                server_default="male",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("sex")

    # ### end Alembic commands ###
